module.exports = {
	noUserFound: 'There was no user found for that department.',
	incorrectPassword: 'Your password was incorrect.',
	notLoggedIn: 'No user is logged in',
	noEvaluationYearGiven: 'No year for the evaluation was found',
	noEvaluationFound: 'No evaluation with that id was found.',
	noEvaluationIdGiven: 'No id for an evaluation was given',
	noMissionStatementGiven: 'No update for the mission statement was found',
	noGoalIdGiven: 'No id for a goal was given',
	noGoalGiven: 'No update for the goal was found',
	noGoalNameGiven: 'No update for the name of the goal was found',
	noGoalFound: 'No goal with that id was found.',
	noSLOIdGiven: 'No id for a student learning objective was found',
	noSLOGiven: 'No update for the student learning objective was found',
	noSLONameGiven: 'No update for the name of the student learning objective was found',
	noSLOFound: 'No student learning objective with that id was found',
	noProcessIdGiven: 'No id for a process was given',
	noProcessGiven: 'No update for the process was found',
	noProcessNameGiven: 'No update for the name of the process was given',
	noProcessFound: 'No process with that id was found',
	noResultGiven: 'No update for the result was found',
	noResultNameGiven: 'No update for the name of the result was given'
}